#!/bin/bash

#Ejecutar script desde Github directamente:
#via curl:
#sh -c "$(curl -fsSL https://raw.githubusercontent.com/hackingyseguridad/scan/master/miip2)"
#via wget:
#sh -c "$(wget -qO- https://raw.githubusercontent.com/hackingyseguridad/scan/master/miip2)"
# o via fetch:
#sh -c "$(fetch -o - https://raw.githubusercontent.com/hackingyseguridad/scan/master/miip2)"

cat << "INFO"
            _ _      ___
           (_|_)    |__ \
  _ __ ___  _ _ _ __   ) |
 | '_ ` _ \| | | '_ \ / /
 | | | | | | | | |_) / /_
 |_| |_| |_|_|_| .__/____| v.1.0
               | |  miip ( Version Kali Linux )
               |_|  www.hackingyseguridad.com
INFO
echo
echo "Sistema: " $(uname -o)
echo
echo "Version: " $(cat /etc/os-release | grep ^VERSION= | cut -f2 -d\")
echo
echo "Distribucion: " $(cat /etc/os-release | grep ^NAME= | cut -f2 -d\")
echo
echo "Architectura: " $(uname -m)
echo
echo "Version Kernel: " $(uname -r)
echo
echo "Carga promedio: $(cat /proc/loadavg | cut -f 1-3 -d ' ')"
echo
echo "Tiempo actividad: " $(uptime -p | cut -f 2- -d " ")
echo
echo "Hostname: " $HOSTNAME
echo
echo "IP interna: " $(hostname -I)
echo
echo "MAC Address " $(arp -n )
echo
echo "Gateway: " $(ip route show 0.0.0.0/0)
echo
echo "Mascara: " $(ifconfig |grep netmask)
echo
echo "IP publica: " $(wget http://ipinfo.io/ip -qO -)
echo
echo "DNS: " $(cat /etc/resolv.conf | grep 'nameserver' | awk '{print $2}')
echo
echo "Usuarios logueados:\n$(who)"
echo
echo "Usuario actual: " $(whoami)
echo
echo "Memoria usada: \n$(free -m | grep -v +)"
echo
echo "Discos: \n$(df -h| grep 'Filesystem\|^/dev/*')"
